### ISSUE TITLE
可以请您分享使用的词向量嘛

### ISSUE THREAD

**Issue by y1041** [HLTCHKUST/sensational_headline#2]
您好
想询问下这个档案 "chinese_emb/sgns.weibo.char"
是这个[网址](https://github.com/Embedding/Chinese-Word-Vectors)里的嘛？
因这里面词向量档案好像失效了 请问有别的适合替代嘛？谢谢

**Comment by jimmy-walker** [comment]
？作者不是已经[分享](https://pan.baidu.com/s/10bhJpaXMCUK02nHvRAttqA)了吗。

**Comment by pxuab** [comment]
谢谢 jimmy-walker的正确回答。

**Comment by y1041** [comment]
您好 谢谢回答 不过我这里看这网页是挂掉的 真奇怪

<img width="410" alt="螢幕快照 2020-03-18 下午12 55 57" src="https://user-images.githubusercontent.com/62011368/76926695-f394c900-6917-11ea-9576-aa4070311edd.png">
