### ISSUE TITLE
如何生成自定义的same_test.txt文件呢？

### ISSUE THREAD

**Issue by jimmy-walker** [HLTCHKUST/sensational_headline#3]
感谢作者的开源分享。
看了下源码，对于Pointer-Gen+ARL-SEN网络的Generation任务，就是载入sensation_lcsts下的same_test.txt文件，最终生成test_prediction结果文件。
想请问下如何将自己的语料生成same_test.txt格式那样的文件呢，因为看到其中有一个分值是sensational score，比如下面的0.00143
```
可 穿戴 技术 十大 设计 原则	0.00143	本文 总结 了 十个 可 穿戴 产品 的 设计 原则 ， 而 这些 原则 ， 同样 也 是 笔者 认为 是 这个 行业 最 吸引 人 的 地方 ： 1 . 为 人们 解决 重复性 问题 ； 2 . 从人 开始 ， 而 不是 从 机器 开始 ； 3 . 要 引起 注意 ， 但 不要 刻意 ； 4 . 提升 用户 能力 ， 而 不是 取代 人
经济学 人 ： 智能手机 将 成为 “ 真正 的 个人电脑 ”	0.01545	2007 年 乔布斯 向 人们 展示 iPhone 并 宣称 “ 它 将 会 改变 世界 ” ， 还有 人 认为 他 在 夸大其词 ， 然而 在 8 年 后 ， 以 iPhone 为 代表 的 触屏 智能手机 已经 席卷 全球 各个 角落 。 未来 ， 智能手机 将会 成为 “ 真正 的 个人电脑 ” ， 为 人类 发展 做出 更大 的 贡献 。
```

**Comment by pxuab** [comment]
如果是自己的语料库的话，可以把sensational score设置成0.0，生成的过程并不依赖这个score。

**Comment by jimmy-walker** [comment]
> 如果是自己的语料库的话，可以把sensational score设置成0.0，生成的过程并不依赖这个score。

谢谢你啊。我刚用pytorch，不是很熟。想问下从这个文件`same_test.txt`中读取的`headline`会被一起训练是吗。还是直接把article输入pointer网络和强化学习，headline也只是和score一样最后输出使用呢？
```python
def read_langs(file_name, thd=0.0):
                d["x"] = article
                d["y"] = headline
                d["s"] = float(score)
```

**Comment by pxuab** [comment]
test中的headline不会也不能被拿来训练，只是在计算score的时候，可能用到。

**Comment by jimmy-walker** [comment]
@pxuab  好的，谢谢你，那我暂时先生成个伪headline，0.0，再加上jieba分词后的文本作为same_test.txt。然后之后再读读源码。
