### ISSUE TITLE
problem about rouge score

### ISSUE THREAD

**Issue by river0tter** [HLTCHKUST/sensational_headline#4]
Hi, I was confusing that why you use "article" as the ground truth to compute rouge score in the below codes? However, as you mentioned in the paper, it seemed that y* should be "headline".
THX :) 

<img width="895" alt="Screen Shot 2020-05-29 at 13 17 01" src="https://user-images.githubusercontent.com/65056117/83223911-b1f18b80-a1ae-11ea-853d-7723ed3bd846.png">

**Comment by pxuab** [comment]
Yes, the rouge score is between headlines. This function was used for experiments with one of our new ROUGE rewards, such as ROUGE score with "article". In the end, we did not use this reward but only use the sensation reward.

**Comment by river0tter** [comment]
I understood. Thanks for your answer.
